page_about/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
     url(r'^$', index, name='index')
]

page_contact/urls.py
from django.conf.urls import url
from .views import index, add_comment

urlpatterns = [
     url(r'^$', index, name='index'),
     url(r'^add_comment', add_comment, name='add_comment')
]

page_landing/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
     url(r'^$', index, name='index')
]

porto/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
import page_landing.urls as landing
import page_about.urls as about
import page_contact.urls as contact

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', include(('page_landing.urls', 'page_landing'), namespace='page_landing')),
    url(r'^about/', include(('page_about.urls', 'page_about'), namespace='page_about')),
    url(r'^contact/', include(('page_contact.urls', 'page_contact'), namespace='page_contact'))
    ]

page_about/models.py
from django.db import models

# Create your models here.

page_contact/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
    nama = models.CharField(max_length=27)
    comment = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

page_landing/models.py
from django.db import models

# Create your models here.

page_about/views.py
from django.shortcuts import render

# Create your views here.
response={}
def index(request):
    return render(request, 'about.html', response)

page_contact/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Comment


# Create your views here.
response={}
def index(request):
    comments = Comment.objects.all().order_by('-created_date')
    response['comments'] = comments
    return render(request, 'contact.html', response)

def add_comment(request):
    if request.method == "POST":
        nama = request.POST['Name']
        if nama == '':
            nama = "anonymous"
        isi = request.POST['Comment']
        Comment.objects.create(nama=nama, comment=isi)
        # Comment.save()
    return HttpResponseRedirect('/contact/')

page_landing/views.py
from django.shortcuts import render

# Create your views here.
response={}
def index(request):
    return render(request, 'landing.html', response)

page_about/templates/about.html
{% load staticfiles %}
<!DOCTYPE html>
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'css/about.css' %}" />
  <link href="https://fonts.googleapis.com/css?family=Raleway:200,100,400" rel="stylesheet" type="text/css" />
</head>
<body>
  <a onclick="togglenight()" class="moon"></a>
  <div onclick="navbaropen()" class="burger" >
    <a class="burger-line"></a>
    <a class="burger-line"></a>
    <a class="burger-line"></a>
  </div>
<div class="navbar">
<a class="nav-link" href="/">Home</a><a class="nav-link" href="/about">About</a><a class="nav-link"href="/contact/">Contacts</a>
</div>
  <div class="container">
    <div class="about">
      <h1 class="name">Nadyah Hani Ramadhana</h1>
      <img class="photo" src="https://instagram.fcgk12-1.fna.fbcdn.net/vp/b21998ff41652aea413679f88a0719e2/5CE0FA05/t51.2885-15/e35/20398097_1403726139664469_9001248830955454464_n.jpg?_nc_ht=instagram.fcgk12-1.fna.fbcdn.net">
    </div>
    <div class="about">
      <div class="description">
        <h1>Work Experience</h1>
        <p><b>Rupa Creative</b> &#8212; Videographer Intern</p>
        <p>Rupa Creative is a creative agency and studio located in Tebet. I learnt about making creative decisions, collaborating with people and dealing with working culture differences.</p>
        <br>
        <h1>Program Committee</h1>
        <p><b>Compfest X</b> &#8212; Vice PIC of Photography and Cinematography</p>
        <p>Biggest IT event in Indonesia held by Students. I learnt how to work in a team, time management and learnt many things about the IT industry as I was present in most of the events.</p>
        <br>
        <p><b>The 25th Computers Get Together</b> &#8212; Vice PIC of documentation</p>
        <p>An internal event for computer science students and faculty members of Universitas Indonesia which consists of events aimed at strengthening the bond between students and faculty members.</p>
        <br>
        <h1>Projects</h1>
        <p><b>Bambu Runcing</b> &#8212; ( <a href="https://bamburuncing.github.io">https://bamburuncing.github,io</a> )</p>
        <p>A game of reversi or othello with a premise of playing as Indonesian soldiers against invaders using artificial intelligence with minimax algorithm.</p>
        <br>
        <h1>Education</h1>
        <p><b>Universitas Indonesia</b> &#8212; Fakultas Ilmu Komputer</p>
        <br>
      </div>
      <div class="skills">
        <h2>Skills</h2>
          <p>&#8227; JavaScript</p>
          <p>&#8227; Django</p>
          <p>&#8227; Python</p>
          <p>&#8227; Java</p>
          <p>&#8227; HTML5</p>
          <p>&#8227; CSS</p>
          <p>&#8227; React</p>
        <br>
      </div>
    </div>

  </div>
  <div class="background-shapes">
    <a id="line1" class="shape line"></a>
    <a id="line2"class="shape x"></a>
    <a id="line3"class="shape circle"></a>
    <a id="line4"class="shape square-bg"></a>
    <a id="line5"class="shape line"></a>
    <a id="line6"class="shape x"></a>
    <a id="line7"class="shape square-bg"></a>
    <a id="line8"class="shape line"></a>
    <a id="line9"class="shape x"></a>
    <a id="line10"class="shape line"></a>
  </div>
</body>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="{% static 'js/about.js' %}"></script>

page_contact/templates/contact.html
{% load staticfiles %}
<!DOCTYPE html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Raleway:200,100,400" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <div id="phone-modal"class="modal" onClick="closeModal()">
      <div class="modal-box">
        <p>Phone/ WhatsApp : 087781677523</p>
      </div>
    </div>
    <div id="email-modal"class="modal" onClick="closeModal()">
      <div class="modal-box">
        <p>Gmail : hani.nadyah@gmail.com</p>
      </div>
    </div>
    <a onclick="togglenight()" class="moon"></a>
      <div onclick="navbaropen()" class="burger" >
          <a class="burger-line"></a>
          <a class="burger-line"></a>
          <a class="burger-line"></a>
        </div>
      <div class="navbar">
      <a class="nav-link" href="/">Home</a><a class="nav-link" href="/about">About</a><a class="nav-link"href="/contact">Contacts</a>
      </div>
      <h2 class="comment-title">Leave a message!</h2>
      <div class="container">
        <div class="comment-form">
        <form id="form" method="POST" action="{% url 'page_contact:add_comment' %}">
            {% csrf_token %}
          <input class="flex-item name-input" type="text" name="Name" placeholder="Your Name">
          <textarea style="resize : none;"class="flex-item comment-input" rows=10 type="text" name="Comment" placeholder="Your Message" required></textarea>
          <button class="flex-item" type="submit" value="Submit">Submit</button>
        </form>
      </div>

      <div class="comment-container">
        {% if comments %}
        {% for comment in comments %}
          <div class="comment">
          <h3>{{ comment.nama }}</h3>
          <p class="isi-comment">{{ comment.comment }}</p>
          <p>{{ comment.created_date }}</p>
        </div>
        {% endfor %}
        {% else %}
        <h3 style="margin : 10px;">No messages to show ;(</h3>
        {% endif %}
      </div>
    </div>
    <div class="social-media">
      <a onClick="showModal('phone-modal')">
      <img class="socmed-icon" src="{% static 'images/phone.png' %}"/>
      </a>
      <a onClick="showModal('email-modal')">
      <img class="socmed-icon" src="{% static 'images/mail.png' %}"/>
    </a>
    <a href="https://linkedin.com/in/nadyahhani">
      <img class="socmed-icon" src="{% static 'images/linkedin.png' %}" />
    </a>
    <a href="https://instagram.com/nadyahhani">
      <img class="socmed-icon" src="{% static 'images/instagram.png' %}" />
    </a>
    </div>
      <div class="background-shapes">
        <a id="line1" class="shape line"></a>
        <a id="line2"class="shape x"></a>
        <a id="line3"class="shape circle"></a>
        <a id="line4"class="shape square-bg"></a>
        <a id="line5"class="shape line"></a>
        <a id="line6"class="shape x"></a>
        <a id="line7"class="shape square-bg"></a>
        <a id="line8"class="shape line"></a>
        <a id="line9"class="shape x"></a>
        <a id="line10"class="shape line"></a>
      </div>
  </body>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script src="{% static 'js/contact.js' %}"></script>

page_landing/templates/landing.html
{% load staticfiles %}
<!DOCTYPE html>
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'css/landing.css' %}" />
  <link rel="stylesheet" type="text/js" href="{% static 'js/landing.js' %}" />
  <link href="https://fonts.googleapis.com/css?family=Raleway:200,100,400" rel="stylesheet" type="text/css" />
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
</head>
<body>
  <div id="loading-screen">
    <a id="loading-logo" class="spin"></a>
  </div>
  <a onclick="togglenight()" class="moon"></a>
  <div onclick="navbaropen()" class="burger" >
    <a class="burger-line"></a>
    <a class="burger-line"></a>
    <a class="burger-line"></a>
  </div>
<div class="navbar">
<a class="nav-link" href="/">Home</a><a class="nav-link" href="/about/">About</a><a class="nav-link" href="/contact/">Contacts</a>
</div>
  <div class="parallax">
    <div class="parallax-layer layer-3">
      <a id="line1" class="shape line"></a>
      <a id="line2"class="shape x"></a>
      <a id="line3"class="shape circle"></a>
      <a id="line4"class="shape square-bg"></a>
      <a id="line5"class="shape line"></a>
      <a id="line6"class="shape x"></a>
      <a id="line7"class="shape square-bg"></a>
      <a id="line8"class="shape line"></a>
      <a id="line9"class="shape x"></a>
      <a id="line10"class="shape line"></a>
    </div>

    <div class="parallax-layer layer-2">
      <div class="flex-image">
        <div class="left-squares-image">

        </div>
        <div class="right-squares-image">
          <img class="foto-right img-portrait" src="{% static 'images/IMG_8341-1.jpg' %}">
          <img class="foto-right img-portrait" src="{% static 'images/DSC09107-6.jpg' %}">
          <img class="foto-right img-portrait" src="{% static 'images/ORG_PHY00284-7.jpg' %}">
        </div>
    </div>

    </div>
    <div class="parallax-layer layer-1">
      <div class="flex-image">
        <div class="left-squares-image">
          <img class="foto img-portrait" src="{% static 'images/IMG_8362-4.jpg' %}">
          <img class="foto img-portrait" src="{% static 'images/IMG-WURI.jpg' %}">
          <img class="foto img-portrait" src="{% static 'images/ORG_PHY00354-8.jpg' %}">
          <img class="foto img-square" src="{% static 'images/IMG_3667-12.jpg' %}">
        </div>
        <div class="right-squares-image">
        </div>
    </div>
    <div class="video-section container">
      <h1>Videos</h1>
      <iframe width='1280' height='753' src="https://www.youtube.com/embed/926HG5RXdCE?&theme=dark&autohide=2&modestbranding=1&fs=0&showinfo=0&rel=0&iv_load_policy=3"frameborder="0"></iframe>
        <iframe width='1280' height='753' src="https://www.youtube.com/embed/AO0gDX89Tog?&theme=dark&autohide=2&modestbranding=1&fs=0&showinfo=0&rel=0&iv_load_policy=3"frameborder="0"></iframe>
    </div>

    </div>
    <div class="parallax-layer layer-4">

<h1 class="title"> I am 
  <span
     class="txt-rotate"
     data-period="2000"
     data-rotate='[ "Nadyah.", "a student.", "a photographer.", "a programmer.", "a videographer."]'></span>
</h1>
    </div>

  </div>



</body>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="{% static 'js/landing.js' %}"></script>
</html>